---
title: "STATS 531 Winter 2022 <br>Midterm projects"
output:
  html_document:
      toc: yes
---

---------

* Projects are posted anonymously below. Source code and data are available from [https://github.com/ionides/531w24/midterm_project](https://github.com/ionides/531w24/tree/master/midterm_project).

* After the course is over and the class grades are assigned, you may choose to request to have your name attached to your project.

----------

| | 
|:----|:----|
| 1.  [NYC Traffic Accidents](midterm_project/project01/blinded.html)  | 
| 2.  [Bitcoin and Dogecoin](midterm_project/project02/blinded.html)  | 
| 3.  [Unemployment and Federal Interest Rate](midterm_project/project03/blinded.html)  | 
| 4.  [CO2 emmision in the US](midterm_project/project04/blinded.html)  | 
| 5.  [US Vehicle Sales](midterm_project/project05/blinded.html)  | 
| 6.  [Power Consumption](midterm_project/project06/blinded.html)  | 
| 7.  [Precipitation in Detroit](midterm_project/project07/blinded.html)  | 
| 8.  [Solar Wind](midterm_project/project08/blinded.html)  | 
| 9.  [Sunspots](midterm_project/project09/blinded.html)  | 
| 10.  [Bitcoin](midterm_project/project10/blinded.html) | 
| 11.  [Wind Power Production](midterm_project/project11/blinded.html) | 
| 12.  [Household Electricity Consumption](midterm_project/project12/blinded.html) | 
| 13.  [Political Regimes](midterm_project/project13/blinded.html) | 
| 14.  [Apple Stock Price](midterm_project/project14/blinded.html) | 
| 15.  [Nvidia Stock Price](midterm_project/project15/blinded.html) | 
| 16.  [Sales of Electric Vehicles in the US](midterm_project/project16/blinded.html) | 

<!-- | | | -->
<!-- |:----|:----| -->
<!-- | 1.  [](midterm_project/project01/blinded.html)  | [Review comments](project01/comments.html) | -->
<!-- | 2.  [](midterm_project/project02/blinded.html)  | [Review comments](project02/comments.html) | -->
<!-- | 3.  [](midterm_project/project03/blinded.html)  | [Review comments](project03/comments.html) | -->
<!-- | 4.  [](midterm_project/project04/blinded.html)  | [Review comments](project04/comments.html) | -->
<!-- | 5.  [](midterm_project/project05/blinded.html)  | [Review comments](project05/comments.html) | -->
<!-- | 6.  [](midterm_project/project06/blinded.html)  | [Review comments](project06/comments.html) | -->
<!-- | 7.  [](midterm_project/project07/blinded.html)  | [Review comments](project07/comments.html) | -->
<!-- | 8.  [](midterm_project/project08/blinded.html)  | [Review comments](project08/comments.html) | -->
<!-- | 9.  [](midterm_project/project09/blinded.html)  | [Review comments](project09/comments.html) | -->
<!-- | 10.  [](midterm_project/project10/blinded.html) | [Review comments](project10/comments.html) | -->
<!-- | 11.  [](midterm_project/project11/blinded.html) | [Review comments](project11/comments.html) | -->
<!-- | 12.  [](midterm_project/project12/blinded.html) | [Review comments](project12/comments.html) | -->
<!-- | 13.  [](midterm_project/project13/blinded.html) | [Review comments](project13/comments.html) | -->
<!-- | 14.  [](midterm_project/project14/blinded.html) | [Review comments](project14/comments.html) | -->
<!-- | 15.  [](midterm_project/project15/blinded.html) | [Review comments](project15/comments.html) | -->
<!-- | 16.  [](midterm_project/project16/blinded.html) | [Review comments](project16/comments.html) | -->

----------
